pipeline {
    agent any
    environment {
        REGISTRY = "<ec2-ip>:5000"
        IMAGE = "nginx-k3s"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t $REGISTRY/$IMAGE:latest .'
            }
        }
        stage('Push') {
            steps {
                sh 'docker push $REGISTRY/$IMAGE:latest'
            }
        }
        stage('Update Deployment') {
            steps {
                sh '''
                git config --global user.email "jenkins@example.com"
                git config --global user.name "Jenkins"
                sed -i "s|image:.*|image: $REGISTRY/$IMAGE:latest|" k8s/deployment.yaml
                git add k8s/deployment.yaml
                git commit -m "Update image to latest"
                git push origin main
                '''
            }
        }
    }
}

